Shared memory/m fatin
SWTec/cppinternship21-phase1 pull request #46
Opened 2021-09-26 16:44 UTC by MFatinSWTEC

[HW][Shared ptr] MFatin

2021-09-27 21:38 UTC, kselar requested changes
The main concern here is that the solution is much more complex than task requires. This is not bad (until we start working on agile), but will take more time than it could.

2021-09-27 21:38 UTC, kselar commented on shared_memory/MFatin/MFatin/MFatin.cpp
> +// class Deleter = std::conditional<std::is_array_v<T>, DefaultArrayDeleter, DefaultPointerDeleter>
This can be used in template specialization, I guess.

2021-09-27 21:38 UTC, kselar commented on shared_memory/MFatin/MFatin/shared_smart_pointer.h
> +		delete[] ptr;
Which one isn't working? Is this one? @MFatinSWTEC, could you share an example?

2021-09-27 22:21 UTC, MFatinSWTEC commented on shared_memory/MFatin/MFatin/shared_smart_pointer.h
> +	return shared_ptr1<T>(new T(std::forward<Args>(args)...));
Could you clarify this statement "But constructing in place is more correct". Do you mean placemant new?

2021-09-27 22:26 UTC, MFatinSWTEC commented on shared_memory/MFatin/MFatin/shared_smart_pointer.h
> +		delete[] ptr;
I'm not shure about memory allocation for array, because I don't know the way to provide data on allocated size of array. I deleted this class in my last commit

2021-09-29 08:09 UTC, kselar requested changes

2021-09-29 08:09 UTC, kselar commented on shared_memory/MFatin/MFatin/shared_smart_pointer.h
> +	return shared_ptr1<T>(std::forward<Args>(args)...);
@MFatinSWTEC, could you add a ctor in `shared_ptr1` class for the case with forwarded args?

2021-09-29 08:09 UTC, kselar commented on shared_memory/MFatin/MFatin/shared_smart_pointer.h
> +	shared_ptr1(const shared_ptr1&& sh) : data{ sh.data }, instanceCount{ sh.instanceCount } {
Why const? 
@MFatinSWTEC, could you add moves for the data inside of `shared_ptr1` class. If `std::move` doesn't cleans moved pointers with VC compiler it doesn't mean that it should be ignored.

2021-09-29 08:09 UTC, kselar commented on shared_memory/MFatin/MFatin/shared_smart_pointer.h
> +		sh.instanceCount = nullptr;
Should we also clear `data`?

2021-09-29 15:23 UTC, kselar reviewed
@MFatinSWTEC, could you delete all unnecessary files? Project ones and empty.

2021-09-29 15:23 UTC, kselar commented on shared_memory/MFatin/MFatin/MFatin.vcxproj
> +<?xml version="1.0" encoding="utf-8"?>
These are all project files which are not needed

2021-09-29 17:48 UTC, kselar approved these changes

2021-09-29 17:48 UTC, merged