[HW][Lambda][Tests 0, 3, 4]
SWTec/cppinternship21-phase1 pull request #56
Opened 2021-09-30 10:04 UTC by AKalistratov

Tests 0, 3 and 4 passed.

2021-09-30 13:52 UTC, kselar requested changes
@AKalistratov, could you repeat test 3 several times in a row? Will it pass every time?
Command arguments:
--gtest_filter=LambdaTest.Capture_Test_Example_3 --gtest_repeat=10

2021-09-30 13:52 UTC, kselar commented on json_project/test/objects/Util.cc
> +		engine.deserialize(host, query, stringObject);
Cheating) But OK.

2021-09-30 13:52 UTC, kselar commented on json_project/test/objects/ObjectBase.h
> +		setValue("name", callback());
Cheating. @AKalistratov, could you avoid implementing of new `asyncDeserialize`?
We can discuss it if it is not clear how to do so.

2021-10-01 07:33 UTC, AKalistratov commented
Do I need to leave the asyncDeserialize which is on line 34 in the Util.cc file?

2021-10-01 07:47 UTC, kselar commented
@AKalistratov, that one is for test 3 and is OK. I mean the one added to fix test 4.

2021-10-04 12:41 UTC, kselar requested changes

2021-10-04 12:41 UTC, kselar commented on json_project/test/lambda_test.cc
> +        auto lambda = [&stringObject]() {
@AKalistratov, the fix can be done without changes in test itself.
The clue is to remove cross reference between lambda and object in time.

2021-10-05 20:41 UTC, kselar commented
Closing to clean up.

2021-10-05 20:41 UTC, closed without merging